# Generated by Django 5.2 on 2026-06-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], default='Open', max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('complaint_description', models.TextField(default='Not Provided')),
                ('batch_order', models.CharField(max_length=100)),
                ('justification_from_factory', models.TextField(blank=True, default='Not Provided', null=True)),
                ('action_from_factory', models.TextField(blank=True, default='Not Provided', null=True)),
                ('cad_date', models.DateField(blank=True, null=True)),
                ('updated_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='management.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Channel', 'Channel'), ('Country', 'Country'), ('Reported By', 'Reported By'), ('Type', 'Type'), ('Series', 'Series'), ('Material', 'Material'), ('Region', 'Region')], max_length=50)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='case_sub_category',
            field=models.ForeignKey(limit_choices_to={'category': 'Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_case_sub_category', to='management.mastersetting'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'category': 'Channel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_channel', to='management.mastersetting'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='country',
            field=models.ForeignKey(limit_choices_to={'category': 'Country'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_country', to='management.mastersetting'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='material',
            field=models.ForeignKey(limit_choices_to={'category': 'Material'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_material', to='management.mastersetting'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='person',
            field=models.ForeignKey(limit_choices_to={'category': 'Reported By'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_person', to='management.mastersetting'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='series',
            field=models.ForeignKey(limit_choices_to={'category': 'Series'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_series', to='management.mastersetting'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='management.brand')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.model'),
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus_by_region', to='management.mastersetting')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='management.sku'),
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodels', to='management.model')),
            ],
            options={
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='sub_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.submodel'),
        ),
        migrations.CreateModel(
            name='YearRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.PositiveSmallIntegerField()),
                ('year_end', models.PositiveSmallIntegerField()),
                ('number_of_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('layout_code', models.CharField(max_length=100, unique=True)),
                ('sub_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_ranges', to='management.submodel')),
            ],
            options={
                'unique_together': {('sub_model', 'year_start', 'year_end')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.yearrange'),
        ),
    ]
