# Generated by Django 5.2 on 2026-07-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'category': 'Channel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_as_channel', to='management.mastersetting'),
        ),
    ]
