# Generated by Django 5.2.16 on 2026-07-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_complaint_assigned_factory_executive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintapproval',
            name='review_stage',
            field=models.CharField(choices=[('initial', 'Initial approval'), ('reconsideration', 'Rejection reconsideration')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='complaintapproval',
            name='trigger_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconsideration_approvals', to='management.complaintapproval'),
        ),
        migrations.AlterField(
            model_name='complaintapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=10),
        ),
    ]
