# Generated by Django 5.2.16 on 2026-07-24 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_complaintapproval_review_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('pattern', 'Pattern Complaint'), ('production', 'Production Complaint'), ('line', 'Line Complaint')], db_index=True, default='pattern', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], db_index=True, default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='workflow_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('assigned_to_factory', 'Assigned to Factory'), ('factory_review', 'Factory Review'), ('awaiting_approval', 'Awaiting Approval'), ('partially_approved', 'Partially Approved'), ('rework_required', 'Rework Required'), ('approved', 'Approved'), ('action_in_progress', 'Action In Progress'), ('pending_final_update', 'Pending Final Update'), ('closed', 'Closed'), ('on_hold', 'On Hold')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AddIndex(
            model_name='complaintapproval',
            index=models.Index(fields=['approver_user', 'status'], name='idx_approval_user_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_created'),
        ),
    ]
