# Generated by Django 5.2.16 on 2026-08-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_complaint_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearrange',
            name='measurement_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_ranges_by_measurement_country', to='management.mastersetting'),
        ),
        migrations.AddField(
            model_name='yearrange',
            name='vehicle_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_ranges_by_vehicle_country', to='management.mastersetting'),
        ),
    ]
