# Generated by Django 5.2.16 on 2026-08-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
