# Generated by Django 5.2.17 on 2026-09-01 20:43

import django.db.models.deletion
import management.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_add_factory_complaint_registrar_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintMediaUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=management.models.complaint_media_upload_expiry)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_upload_batches', to='management.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_media_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintMediaUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('expected_content_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attached', 'Attached'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_media_uploads', to='management.complaint')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='management.complaintmediauploadbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='complaintmediauploadbatch',
            index=models.Index(fields=['user', 'expires_at'], name='management__user_id_ae38e4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintmediaupload',
            index=models.Index(fields=['status', 'created_at'], name='management__status_ee7e59_idx'),
        ),
    ]
