# Generated by Django 5.2.17 on 2026-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_enforce_non_country_executive_india'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearrange',
            name='fitting_confirmation',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fitting Confirmation'),
        ),
        migrations.AddField(
            model_name='yearrange',
            name='x_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='X-Code'),
        ),
        migrations.AlterField(
            model_name='yearrange',
            name='layout_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
