# Generated by Django 5.2.17 on 2026-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_yearrange_fitting_confirmation_yearrange_x_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='batch_order',
            new_name='batch_no',
        ),
        migrations.AddField(
            model_name='complaint',
            name='serial_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='shipment_order_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
