# Generated by Django 5.2.17 on 2026-09-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_complaint_batch_no_patterndesignfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterndesignfolder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_folders', to='management.yearrange'),
        ),
    ]
