# Generated by Django 5.2.17 on 2026-09-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_patterndesignfolder_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterndesignimage',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_design_images', to='management.yearrange'),
        ),
        migrations.AddField(
            model_name='yearrange',
            name='google_drive_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Google Drive URL'),
        ),
        migrations.AlterField(
            model_name='patterndesignimage',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='management.patterndesignfolder'),
        ),
    ]
