# Generated by Django 5.2.17 on 2026-09-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_patterndesignimage_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearrange',
            name='year_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearrange',
            name='year_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
