# Generated by Django 5.2.17 on 2026-09-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_yearrange_year_end_alter_yearrange_year_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearrange',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Serial Number'),
        ),
    ]
