# Generated by Django 5.2.17 on 2026-09-07 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_yearrange_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['recipient', 'sender', '-created_at'], name='idx_chat_incoming_time'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['recipient', '-created_at'], name='idx_chat_unread_time'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['country', 'workflow_status', '-date'], name='idx_cmp_country_flow_date'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_factory_executive', 'workflow_status'], name='idx_cmp_factory_flow'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_by', '-date'], name='idx_cmp_creator_date'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_type', '-date'], name='idx_cmp_type_date'),
        ),
        migrations.AddIndex(
            model_name='complaintapproval',
            index=models.Index(fields=['approver_user', 'status', 'review_stage'], name='idx_appr_user_state_stage'),
        ),
        migrations.AddIndex(
            model_name='complaintapproval',
            index=models.Index(fields=['complaint', 'approval_round', 'review_stage'], name='idx_appr_cmp_round_stage'),
        ),
        migrations.AddIndex(
            model_name='patterndesignfolder',
            index=models.Index(fields=['vehicle', '-created_at'], name='idx_design_folder_vehicle'),
        ),
        migrations.AddIndex(
            model_name='patterndesignimage',
            index=models.Index(fields=['vehicle', 'folder', '-uploaded_at'], name='idx_design_image_vehicle'),
        ),
    ]
