# Generated by Django 5.2.17 on 2026-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterndesignimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='pattern_design_thumbnails/%Y/%m/'),
        ),
    ]
