# Generated by Django 5.2.17 on 2026-09-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_patternalteration_notification_alteration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterneditlog',
            name='pattern_serial',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patterneditlog',
            name='year_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='management.yearrange'),
        ),
    ]
