# Generated by Django 5.2.17 on 2026-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_remove_yearrange_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('country_executive', 'Country Executive'), ('factory_viewer', 'Factory Viewer'), ('factory_executive', 'Factory Executive'), ('factory_complaint_registrar', 'Factory Complaint Registrar'), ('approver', 'Approver'), ('admin', 'Admin'), ('freelance_3d_designer', '3D Designer Freelancer')], default='factory_viewer', max_length=30),
        ),
    ]
