# Generated by Django 5.2.17 on 2026-09-29 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_add_freelance_3d_designer_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patterndesignimage',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='patterndesignimage',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patterndesignimage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_design_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patterndesignimage',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patterndesignimage',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_design_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patterndesignimage',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='patterndesignimage',
            index=models.Index(fields=['approval_status', '-uploaded_at'], name='idx_design_img_approval'),
        ),
    ]
