# Generated by Django 5.2.17 on 2026-10-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_yearrange_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterndesignimage',
            name='image',
            field=models.FileField(upload_to='pattern_designs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='patterndesignimage',
            name='thumbnail',
            field=models.FileField(blank=True, default='', upload_to='pattern_design_thumbnails/%Y/%m/'),
        ),
    ]
