# Generated by Django 5.2.17 on 2026-10-06 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='design_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='management.patterndesignimage'),
        ),
        migrations.CreateModel(
            name='PatternDesignApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('partially_approved', 'Partially Approved'), ('approved', 'Approved'), ('rejected', 'Changes Required')], db_index=True, default='pending', max_length=25)),
                ('cad_status', models.CharField(default='pending', max_length=20)),
                ('cad_comment', models.TextField(blank=True, default='')),
                ('cad_decided_at', models.DateTimeField(blank=True, null=True)),
                ('ed_status', models.CharField(default='pending', max_length=20)),
                ('ed_comment', models.TextField(blank=True, default='')),
                ('ed_decided_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cad_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cad_design_reviews', to=settings.AUTH_USER_MODEL)),
                ('design_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='management.patterndesignimage')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('ed_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ed_design_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['design_image', 'cycle'], name='idx_design_appr_cycle'), models.Index(fields=['status', '-submitted_at'], name='idx_design_appr_status')],
                'unique_together': {('design_image', 'cycle')},
            },
        ),
    ]
