# Generated by Django 5.2.17 on 2026-10-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_drive_urls(apps, schema_editor):
    YearRange = apps.get_model('management', 'YearRange')
    VehicleDriveLink = apps.get_model('management', 'VehicleDriveLink')
    links = []
    for yr in YearRange.objects.exclude(google_drive_url='').iterator():
        url = (yr.google_drive_url or '').strip()
        if url:
            links.append(VehicleDriveLink(vehicle=yr, url=url, title='Google Drive Folder'))
    if links:
        VehicleDriveLink.objects.bulk_create(links)


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_notification_design_image_patterndesignapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Drive URL')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title / Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drive_links', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_links', to='management.yearrange')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-created_at'], name='idx_v_drive_link_created')],
            },
        ),
        migrations.RunPython(migrate_existing_drive_urls, migrations.RunPython.noop),
    ]
