# Generated by Django 5.2.17 on 2026-10-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_patterndesignimage_client_upload_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledrivelink',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=64),
        ),
    ]
