# pyrefly: ignore [missing-import]
from django.urls import path
from django.contrib.auth.views import LogoutView
from .security import RateLimitedLoginView
from . import views
from .api_views import (
    LoginAPIView, LogoutAPIView, RegisterAPIView, UserProfileAPIView, DashboardAPIView,
    ComplaintListCreateAPIView, ComplaintRetrieveUpdateDestroyAPIView,
    FactoryReviewAPIView, ApprovalInboxAPIView, ApprovalDecisionAPIView,
    ComplaintStartActionAPIView, ComplaintFinalUpdateAPIView,
    NotificationListAPIView, NotificationReadAPIView,
    SKUListCreateAPIView, SKURetrieveUpdateDestroyAPIView,
    VehicleListCreateAPIView, VehicleRetrieveUpdateDestroyAPIView
)

urlpatterns = [
    # REST API Auth Routes
    path('api/auth/login/', LoginAPIView.as_view(), name='api_login'),
    path('api/auth/logout/', LogoutAPIView.as_view(), name='api_logout'),
    path('api/auth/register/', RegisterAPIView.as_view(), name='api_register'),
    path('api/user/profile/', UserProfileAPIView.as_view(), name='api_profile'),
    path('api/dashboard/', DashboardAPIView.as_view(), name='api_dashboard'),
    path('api/complaints/', ComplaintListCreateAPIView.as_view(), name='api_complaints_list_create'),
    path('api/complaints/<str:complaint_id>/', ComplaintRetrieveUpdateDestroyAPIView.as_view(), name='api_complaint_detail'),
    path('api/complaints/<str:complaint_id>/factory-review/', FactoryReviewAPIView.as_view(), name='api_factory_review'),
    path('api/approvals/', ApprovalInboxAPIView.as_view(), name='api_approval_inbox'),
    path('api/approvals/<int:approval_id>/decision/', ApprovalDecisionAPIView.as_view(), name='api_approval_decision'),
    path('api/complaints/<str:complaint_id>/start-action/', ComplaintStartActionAPIView.as_view(), name='api_start_action'),
    path('api/complaints/<str:complaint_id>/final-update/', ComplaintFinalUpdateAPIView.as_view(), name='api_final_update'),
    path('api/notifications/', NotificationListAPIView.as_view(), name='api_notifications'),
    path('api/notifications/<int:notification_id>/read/', NotificationReadAPIView.as_view(), name='api_notification_read'),
    path('api/skus/', SKUListCreateAPIView.as_view(), name='api_skus_list_create'),
    path('api/skus/<int:pk>/', SKURetrieveUpdateDestroyAPIView.as_view(), name='api_sku_detail'),
    path('api/vehicles/', VehicleListCreateAPIView.as_view(), name='api_vehicles_list_create'),
    path('api/vehicles/<int:pk>/', VehicleRetrieveUpdateDestroyAPIView.as_view(), name='api_vehicle_detail'),

    path('complaint/edit/<str:complaint_id>/', views.edit_complaint, name='edit_complaint'),
    path('complaint/factory-review/<str:complaint_id>/', views.factory_review_complaint, name='factory_review_complaint'),
    path('approvals/', views.approval_inbox, name='approval_inbox'),
    path('approvals/<int:approval_id>/', views.approval_review, name='approval_review'),
    path('complaint/execute/<str:complaint_id>/', views.execute_complaint, name='execute_complaint'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/<int:notification_id>/open/', views.open_notification, name='open_notification'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('complaint/delete/<str:complaint_id>/', views.delete_complaint, name='delete_complaint'),
    path('login/', RateLimitedLoginView.as_view(template_name='management/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='management/logout_success.html'), name='logout'),
    path('logout-success/', views.logout_success, name='logout_success'),
    path('complaints/', views.complaint_list, name='complaint_list'),
    path('profile/', views.profile_settings, name='profile_settings'),
    path('', views.index, name='index'),
    path('add-car-details/', views.add_car_details, name='add_car_details'),
    path('car-details/', views.car_details, name='car_details'),
    path('delete-car-detail/<int:year_range_id>/', views.delete_car_detail, name='delete_car_detail'),
    path('edit-car/<int:car_id>/', views.edit_car_detail, name='edit_car_detail'),
    path('master-settings/', views.master_settings, name='master_settings'),
    path('edit-master-setting/<int:setting_id>/', views.edit_master_setting, name='edit_master_setting'),
    path('delete-master-setting/<int:setting_id>/', views.delete_master_setting, name='delete_master_setting'),
    path('add-complaint/', views.add_complaint, name='add_complaint'),
    path('api/models/<int:brand_id>/', views.get_models, name='get_models'),
    path('api/sub_models/<int:model_id>/', views.get_sub_models, name='get_sub_models'),
    path('api/year_ranges/<int:sub_model_id>/', views.get_year_ranges, name='get_year_ranges'),
    path('api/filtered-skus/', views.get_filtered_skus, name='get_filtered_skus'),
    path('export_complaints/', views.export_complaints, name='export_complaints'),
    path('upload-cars/', views.upload_car_csv, name='upload_car_csv'),
    path('add-sku/', views.add_sku, name='add_sku'),
    path('delete-sku/<int:sku_id>/', views.delete_sku, name='delete_sku'),
    path('edit-sku/<int:sku_id>/', views.edit_sku, name='edit_sku'),
    path('admin_panel/', views.admin_panel_view, name='admin_panel'),
    path('admin-panel/edit-group/', views.edit_group, name='edit_group'),
    path('admin-panel/delete-group/', views.delete_group, name='delete_group'),
    path('admin-panel/edit-user/', views.edit_user, name='edit_user'),
    path('admin-panel/delete-user/', views.delete_user, name='delete_user'),
    path('admin-panel/terminate-session/<str:session_key>/', views.terminate_session_view, name='terminate_session'),
    path('admin-panel/terminate-all-sessions/', views.terminate_all_sessions_view, name='terminate_all_sessions'),
]
