"""
Django settings for fabro_leather project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import unquote, urlparse
from django.core.exceptions import ImproperlyConfigured

# Load .env file if it exists
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                key, val = line.split('=', 1)
                os.environ.setdefault(key.strip(), val.strip().strip("'\""))


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


E2E_TESTING = env_bool('E2E_TESTING', False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool('DEBUG', True)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'fabro-local-development-key-change-before-production'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY is required when DEBUG is disabled.')
if not DEBUG and (
    len(SECRET_KEY) < 50
    or SECRET_KEY.startswith('django-insecure-')
    or SECRET_KEY == 'replace-with-a-long-random-secret'
):
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be a unique random value of at least 50 characters in production.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '127.0.0.1,localhost,10.0.2.2,.vercel.app' if DEBUG else '.vercel.app,127.0.0.1,localhost')
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['.vercel.app', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'management',
    'simple_history',
]

# Environment-controlled shared caching. Local development and tests need no
# external service; production can opt into Django's built-in Redis backend.
CACHE_URL = os.getenv('CACHE_URL', '').strip()
CACHE_KEY_PREFIX = os.getenv('CACHE_KEY_PREFIX', 'fabro')
if CACHE_URL and not E2E_TESTING:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CACHE_URL,
            'KEY_PREFIX': CACHE_KEY_PREFIX,
            'TIMEOUT': int(os.getenv('CACHE_DEFAULT_TIMEOUT', '300')),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': f'{CACHE_KEY_PREFIX}-local',
        }
    }

BADGE_CACHE_TTL = int(os.getenv('BADGE_CACHE_TTL', '15'))
DASHBOARD_CACHE_TTL = int(os.getenv('DASHBOARD_CACHE_TTL', '45'))
CATALOG_CACHE_TTL = int(os.getenv('CATALOG_CACHE_TTL', '600'))
PERFORMANCE_TIMING_ENABLED = env_bool('PERFORMANCE_TIMING_ENABLED', DEBUG)
SQL_QUERY_COUNT_ENABLED = env_bool('SQL_QUERY_COUNT_ENABLED', False)
SLOW_REQUEST_THRESHOLD_MS = int(os.getenv('SLOW_REQUEST_THRESHOLD_MS', '750'))

S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME', '')
S3_REGION = os.getenv('S3_REGION', 'garage')
S3_ENDPOINT_URL = os.getenv('S3_ENDPOINT_URL', '').rstrip('/')
S3_PUBLIC_ENDPOINT_URL = os.getenv('S3_PUBLIC_ENDPOINT_URL', '').rstrip('/')
S3_ACCESS_KEY_ID = os.getenv('S3_ACCESS_KEY_ID', '')
S3_SECRET_ACCESS_KEY = os.getenv('S3_SECRET_ACCESS_KEY', '')
S3_ADDRESSING_STYLE = os.getenv('S3_ADDRESSING_STYLE', 'path')
S3_SIGNATURE_VERSION = os.getenv('S3_SIGNATURE_VERSION', 's3v4')
S3_SIGNED_UPLOAD_TTL_SECONDS = int(os.getenv('S3_SIGNED_UPLOAD_TTL_SECONDS', '7200'))
S3_SIGNED_DOWNLOAD_TTL_SECONDS = int(os.getenv('S3_SIGNED_DOWNLOAD_TTL_SECONDS', '300'))

S3_REQUIRED_SETTINGS = {
    'S3_BUCKET_NAME': S3_BUCKET_NAME,
    'S3_REGION': S3_REGION,
    'S3_ENDPOINT_URL': S3_ENDPOINT_URL,
    'S3_PUBLIC_ENDPOINT_URL': S3_PUBLIC_ENDPOINT_URL,
    'S3_ACCESS_KEY_ID': S3_ACCESS_KEY_ID,
    'S3_SECRET_ACCESS_KEY': S3_SECRET_ACCESS_KEY,
}
S3_STORAGE_CONFIGURED = all(S3_REQUIRED_SETTINGS.values())
USE_S3_STORAGE = False if E2E_TESTING else env_bool(
    'USE_S3_STORAGE',
    not DEBUG,
)
if USE_S3_STORAGE and not S3_STORAGE_CONFIGURED:
    missing_settings = ', '.join(
        name for name, value in S3_REQUIRED_SETTINGS.items() if not value
    )
    raise ImproperlyConfigured(
        'Production media storage is enabled but required S3 settings are missing: '
        f'{missing_settings}.'
    )

# Backward compatibility alias
USE_SUPABASE_STORAGE = USE_S3_STORAGE
SUPABASE_STORAGE_BUCKET = S3_BUCKET_NAME
SUPABASE_SIGNED_UPLOAD_TTL_SECONDS = S3_SIGNED_UPLOAD_TTL_SECONDS
SUPABASE_SIGNED_DOWNLOAD_TTL_SECONDS = S3_SIGNED_DOWNLOAD_TTL_SECONDS

MEDIA_URL = '/media/'

STORAGES = {
    'default': {
        'BACKEND': (
            'management.storage_backends.S3Storage'
            if USE_S3_STORAGE
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
WHITENOISE_MANIFEST_STRICT = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'management.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'management.middleware.UserProfileLocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'management.middleware.PerformanceTimingMiddleware',
]

ROOT_URLCONF = 'fabro_leather.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'management.context_processors.workflow_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'fabro_leather.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
USE_POSTGRES = env_bool('USE_POSTGRES', False) or bool(DATABASE_URL)
if E2E_TESTING:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / '.e2e.sqlite3',
        }
    }
elif USE_POSTGRES:
    if DATABASE_URL:
        parsed_database_url = urlparse(DATABASE_URL)
        if parsed_database_url.scheme not in {'postgres', 'postgresql'}:
            raise ImproperlyConfigured('DATABASE_URL must use the postgres or postgresql scheme.')
        db_name = unquote(parsed_database_url.path.lstrip('/'))
        db_user = unquote(parsed_database_url.username or '')
        db_password = unquote(parsed_database_url.password or '')
        db_host = parsed_database_url.hostname
        db_port = parsed_database_url.port or 5432
    else:
        db_name = os.getenv('DB_NAME', 'postgres')
        db_user = os.getenv('DB_USER')
        db_password = os.getenv('DB_PASSWORD')
        db_host = os.getenv('DB_HOST')
        db_port = os.getenv('DB_PORT', '5432')

    if not all([db_name, db_user, db_password, db_host]):
        raise ImproperlyConfigured(
            'PostgreSQL requires DATABASE_URL or complete DB_NAME, DB_USER, DB_PASSWORD, and DB_HOST values.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'CONN_MAX_AGE': int(os.getenv('CONN_MAX_AGE', '0' if DEBUG else '60')),
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'connect_timeout': 10,
                'sslmode': 'require',
            },
        }
    }
else:
    db_path = Path('/tmp') / 'db.sqlite3' if os.getenv('VERCEL') else BASE_DIR / 'db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'العربية'),
    ('hi', 'हिन्दी'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_ROOT = BASE_DIR / ('.e2e-media' if E2E_TESTING else 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'logout_success'

# CORS is broad only for explicit local development. Production must list origins.
CORS_ALLOW_ALL_ORIGINS = DEBUG and env_bool('CORS_ALLOW_ALL_ORIGINS', True)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', False)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', 'https://*.vercel.app' if DEBUG else 'https://*.vercel.app')
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']

ALLOW_PUBLIC_REGISTRATION = env_bool('ALLOW_PUBLIC_REGISTRATION', False)
LOGIN_MAX_ATTEMPTS = int(os.getenv('LOGIN_MAX_ATTEMPTS', '8'))
LOGIN_RATE_WINDOW_SECONDS = int(os.getenv('LOGIN_RATE_WINDOW_SECONDS', '300'))
LOGIN_LOCKOUT_SECONDS = int(os.getenv('LOGIN_LOCKOUT_SECONDS', '900'))

_s3_connect_src = ' https://storage.fabroleather.com'
if S3_PUBLIC_ENDPOINT_URL and S3_PUBLIC_ENDPOINT_URL not in _s3_connect_src:
    _s3_connect_src += f' {S3_PUBLIC_ENDPOINT_URL}'

CONTENT_SECURITY_POLICY = os.getenv(
    'CONTENT_SECURITY_POLICY',
    "default-src 'self'; "
    "base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; "
    "script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; "
    "font-src 'self' data:; img-src 'self' data: blob: https:; "
    f"media-src 'self' blob: https:; connect-src 'self'{_s3_connect_src}; worker-src 'self' blob:",
)

# Secure defaults become active automatically when DEBUG is disabled.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
LANGUAGE_COOKIE_NAME = 'fabro_language'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
TRUST_PROXY_HEADERS = env_bool('TRUST_PROXY_HEADERS', False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if TRUST_PROXY_HEADERS else None
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# REST Framework Configurations
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'management.pagination.FabroPageNumberPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('API_ANON_THROTTLE', '30/minute'),
        'user': os.getenv('API_USER_THROTTLE', '300/minute'),
        'login': os.getenv('API_LOGIN_THROTTLE', '10/minute'),
    },
}
